version: '3.8'

services:
  database:
    build: 
      context: ./database
    ports:
      - "6699:6699"
    volumes:
      - ./db_app.db:/data/db
  
  backend:
    build: 
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
      
  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend